config:
  database:
    type: MYSQL
    mysql:
      hostname: "127.0.0.1"
      port: 3306
      database: "database"
      username: "root"
      password: ""
      useSSL: true
      poolSize: 5
      connetionTimeout: 20000
      batchLength: 1000
    sqlite:
      fileName: "data.sqlite"
    tableName: "peridrop_users"
  tasks:
    autosave: 900
    ranking-update: 600
  format:
    date: "dd/MM/yyyy HH:mm"
    decimal: "#.##"
  messages:
    drop_status:
      enabled: "&aON"
      disabled: "&cOFF"
    settings_status:
      enabled: "&aON"
      disabled: "&cOFF"
    fortune:
      enabled: "&aON"
      disabled: "&cOFF"
    tool-any: "Kazde"
    biome-any: "Kazdy"
    ranking:
      sign:
        default-text:
          - ""
          - "^^^^^"
          - "Podaj strone"
          - ""
        not-number:
          - ""
          - "^^^^^"
          - "Podaj strone"
          - "&4Bledna strona"
        page-not-exist:
          - ""
          - "^^^^^"
          - "Podaj strone"
          - "&4Bledna strona"
        page-smaller-than-one:
          - ""
          - "^^^^^"
          - "Podaj strone"
          - "&4Bledna strona"
  ranking:
    default-level: 1
    drop-exp:
      min: 1
      max: 3
    level-up:
      required-exp: "level * 1000"
  blocked-drops:
    - EMERALD_ORE:TRUE
    - DIAMOND_ORE:TRUE
    - GOLD_ORE:TRUE
    - LAPIS_ORE:TRUE
    - REDSTONE_ORE:TRUE
    - IRON_ORE:TRUE
    - COAL_ORE:TRUE
    - SPONGE:FALSE
  drop-exp:
    - "STONE:4-6"
    - "OBSIDIAN:8-10"
